### PR TITLE
FCFCampus/ICU: Fix transaction type parse

### PR DESCRIPTION
**Pull request by Qs-F**
FCFCampus/ICU: Fix transaction type parse

### CODE REVIEW

**Comment by treastrain** [comment]
@Qs-F 

I'm sorry. I merged and committed #10.
Is this #9 included in #10?

**Comment by Qs-F** [comment]
@treastrain nope. Thx for your support!

**Comment by Qs-F** [comment]
I accompanied the changes with the upstream.

**Comment by Qs-F** [comment]
thx!

**Pull request merged**
